### ISSUE TITLE
🎯 Add Frontend & Backend Function to Allow or Disallow Votes From Same User 📩

### ISSUE THREAD

**Issue by bauripalash** [bauripalash/pollarboy#2]
## 🎯 Goal
Add Frontend & Backend Function to Allow or Disallow Votes From Same User and Let the Poll Create Allow or Disallow by using a Checkbox while creating the Poll!

## 🕵 Description
Voters can be identified using Cookies (in such case a popup notice must be added for European Union as of GDPR), otherwise IP's can be used but Cookie method is still more reliable.
A Checkbox also must be added to allow Creator to decide to allow multiple votes from same user or not.
Lowdb JSON Database should be used as efficiently as possible.

## 🔨 Skills Required
* Javascript
* NodeJS
* Express
* Nunjucks
* Git
* HTML
* CSS
* Creativity 

## ℹ️ Note 
* A Screenshot Must Be added on PR
* Remixed Glitch Link can also be provided (optional but helpful)
* Keep the Codebase Clean
* Keep The UI & UX clean

**Comment by udaybansal19** [comment]
Can i work on this?

**Comment by bauripalash** [comment]
@udaybansal19, Ofcourse

**Comment by bauripalash** [comment]
@udaybansal19 any updates?

**Comment by udaybansal19** [comment]
It's taking a bit time because i am just a beginner and i don't have much experience with most of the required skills but i am trying to learn them and will try to finish this as soon as possible

**Comment by udaybansal19** [comment]
Opened the pull request, please review it.

**Comment by bauripalash** [comment]
@udaybansal19 , you did an awesome job! 🔥🔥
Please Wait till morning, I'll test and merge your Pull Request 😊
